### ISSUE TITLE
Player instance is not available in `ready` event

### ISSUE THREAD

**Issue by zyrif** [vinayakkulkarni/v-clappr#1345]
Hi,

According to the documentation [here](https://github.com/vinayakkulkarni/v-clappr/blob/b0c34af653d3e3608c297f8cad1747870341bb68/README.md?plain=1#L297), `@ready` event should pass the player instance in it's callback argument.

In it's [code](https://github.com/vinayakkulkarni/v-clappr/blob/b0c34af653d3e3608c297f8cad1747870341bb68/src/components/VClappr.vue#L152), v-clapper expects to receive the player instance as the argument of the callback of `onReady` event. However, `clappr-core` doesn't appear to return the player instance as an argument for this event, as documented [here](https://github.com/clappr/clappr-core/blob/dd2ce655798c19a8cb11a800dfda11a442078140/src/base/events/events.js#L233C1-L233C1). 

As a result, we don't appear to have any way to access the player instance (correct me if I'm wrong). 
This issue is reproducible in the StackBlitz demo, where [this line](https://github.com/vinayakkulkarni/v-clappr/blob/b0c34af653d3e3608c297f8cad1747870341bb68/example/src/App.vue#L81) prints `undefined` in the console:

![image](https://github.com/vinayakkulkarni/v-clappr/assets/24279322/e27710bf-cee5-43f9-90d9-8018d105e8f4)

Also, the example has an [`@init` event ](https://github.com/vinayakkulkarni/v-clappr/blob/b0c34af653d3e3608c297f8cad1747870341bb68/example/src/App.vue#L9) that doesn't appear to fire and is not mentioned in the document. Since this event is no longer available, do we have an alternative way to access the player instance?

**Comment by zyrif** [comment]
Bump

**Comment by zyrif** [comment]
bump

**Comment by zyrif** [comment]
Bump

**Comment by zyrif** [comment]
Bump

**Comment by vinayakkulkarni** [comment]
Player instance should be available in the `init` event, don't use the `ready` event.

Done in v3.4.0
