### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by beiaduo** [vinayakkulkarni/v-clappr#1735]
By default 

npm install v-clappr

pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @clappr/core@0.4.27
npm ERR! node_modules/@clappr/core
npm ERR!   @clappr/core@"^0.4.27" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @clappr/core@"^0.7.2" from v-clappr@3.3.0
npm ERR! node_modules/v-clappr
npm ERR!   v-clappr@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

When I change to 

        "@clappr/core": "^0.7.2",

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @clappr/core@0.7.2
npm ERR! node_modules/@clappr/core
npm ERR!   @clappr/core@"^0.7.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @clappr/core@"^0.4.27" from @clappr/hlsjs-playback@1.3.0
npm ERR! node_modules/@clappr/hlsjs-playback
npm ERR!   @clappr/hlsjs-playback@"^1.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by vinayakkulkarni** [comment]
Can you create stackblitz or a repro where I can reproduce this please?

**Comment by BeiAduo** [comment]
I tried changing 3 computers, same problem;
The first step: Use phpstorm to create a vue3 project, and then
`jasonliu@Jasons-MacBook-Pro-2 untitled % npm install v-clappr
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: untitled@0.0.0
npm ERR! Found: @clappr/core@0.4.27
npm ERR! node_modules/@clappr/core
npm ERR!   @clappr/core@"^0.4.27" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @clappr/core@"^0.7.2" from v-clappr@3.3.0
npm ERR! node_modules/v-clappr
npm ERR!   v-clappr@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-debug-0.log
jasonliu@Jasons-MacBook-Pro-2 untitled % 
`


jasonliu@Jasons-MacBook-Pro-2 ~ % cat /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-debug-0.log
0 verbose cli /opt/homebrew/Cellar/node/21.6.2/bin/node /opt/homebrew/bin/npm
1 info using npm@10.2.4
2 info using node@v21.6.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/jasonliu/untitled/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/jasonliu/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 0ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install v-clappr
22 verbose argv "install" "v-clappr"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-
26 verbose logfile /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 16ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 14ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest v-clappr@*
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/v-clappr 8ms (cache hit)
40 silly fetch manifest @clappr/core@^0.4.27
41 http fetch GET 200 https://registry.npmjs.org/@clappr%2fcore 2ms (cache hit)
42 silly fetch manifest @clappr/core@^0.7.2
43 timing idealTree Completed in 30ms
44 timing command:install Completed in 35ms
45 verbose stack Error: unable to resolve dependency tree
45 verbose stack     at #failPeerConflict (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1376:25)
45 verbose stack     at #loadPeerSet (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1342:33)
45 verbose stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
45 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
45 verbose stack     at async Promise.all (index 1)
45 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
45 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:152:5)
45 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
46 verbose cwd /Users/jasonliu/untitled
47 verbose Darwin 23.4.0
48 verbose node v21.6.2
49 verbose npm  v10.2.4
50 error code ERESOLVE
51 error ERESOLVE unable to resolve dependency tree
52 error
53 error While resolving: untitled@0.0.0
53 error Found: @clappr/core@0.4.27
53 error node_modules/@clappr/core
53 error   @clappr/core@"^0.4.27" from the root project
53 error
53 error Could not resolve dependency:
53 error peer @clappr/core@"^0.7.2" from v-clappr@3.3.0
53 error node_modules/v-clappr
53 error   v-clappr@"*" from the root project
53 error
53 error Fix the upstream dependency conflict, or retry
53 error this command with --force or --legacy-peer-deps
53 error to accept an incorrect (and potentially broken) dependency resolution.
54 error
54 error
54 error For a full report see:
54 error /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-eresolve-report.txt
55 verbose exit 1
56 timing npm Completed in 142ms
57 verbose unfinished npm timer reify 1714860704956
58 verbose unfinished npm timer reify:loadTrees 1714860704959
59 verbose unfinished npm timer idealTree:buildDeps 1714860704975
60 verbose unfinished npm timer idealTree:#root 1714860704975
61 verbose code 1
62 error A complete log of this run can be found in: /Users/jasonliu/.npm/_logs/2024-05-04T22_11_44_850Z-debug-0.log

**Comment by BeiAduo** [comment]
I installed it a few months ago and everything was fine; recently I also wanted to use this plug-in for my new project, but I found that it was not installed; today I tried to update the previous project and found the same problem.

**Comment by BeiAduo** [comment]
This project is very useful. I hope it can be fixed. Thank you.

**Comment by vinayakkulkarni** [comment]
> This project is very useful. I hope it can be fixed. Thank you.

Hey, can you please create a reproducible code? A repo or stackblitz example would be helpful

**Comment by BeiAduo** [comment]
https://github.com/BeiAduo/test_v_clapper Thanks

**Comment by beiaduo** [comment]
It seems that v-clappr depends on @clappr/core": "^0.7.2", but clappr/hlsjs-playback depends on @clappr/core": "^0.4.27"

**Comment by vinayakkulkarni** [comment]
> It seems that v-clappr depends on @clappr/core": "^0.7.2", but clappr/hlsjs-playback depends on @clappr/core": "^0.4.27"
> 
> 

Hopefully I can send out a fix over the weekend. Been a bit busy with work.

**Comment by beiaduo** [comment]
Thanks

**Comment by vinayakkulkarni** [comment]
@beiaduo: the issue should be fixed in `v3.4.0`.
