### ISSUE TITLE
Controls are still visible with `controls` set to `false`

### ISSUE THREAD

**Issue by BastianBrouwers** [vinayakkulkarni/v-clappr#1874]
# Controls are still visible with `controls` set to `false`

Settings:
```html
<v-clappr
        el="preview-player-video__video"
        :source="videoUrl"
        :options="{
          width: '100%',
          height: '100%',
          autoPlay: true,
          playback: {
            preload: 'metadata',
            disableContextMenu: true,
            controls: false,
            playInline: false,
            minimumDvrSize: null,
            externalTracks: [],
            hlsjsConfig: {},
            shakaConfiguration: {},
          },
        }"
      />
 ```
 
 Output:
 
![image](https://github.com/vinayakkulkarni/v-clappr/assets/33203894/beb8484d-b4f4-48a8-ab8c-72e8829281c1)

It seems like the option `controls` only disables the duplicate of controls that appear when `controls` is set to `true`:
![image](https://github.com/vinayakkulkarni/v-clappr/assets/33203894/dc1502b7-0d7b-44b3-a449-e490aa5b5981)

**Comment by vinayakkulkarni** [comment]
Can you please create a stackblitz or codesandbox repro ?
