### ISSUE TITLE
Height and width setting are not adjusted

### ISSUE THREAD

**Issue by yunusberkayaksoy** [vinayakkulkarni/v-clappr#3]
I add to the options object, but the height and width values are not taken.

options: {
    width: '100%',
    height: '100%',
}

**Comment by vinayakkulkarni** [comment]
Ok, I'll take a look.. it's been a long time since I did some housekeeping too for this wrapper.

**Comment by yunusberkayaksoy** [comment]
I am waiting for you to update as soon as possible.
