### ISSUE TITLE
playInLine settings cannot be set

### ISSUE THREAD

**Issue by yunusberkayaksoy** [vinayakkulkarni/v-clappr#6]
playback: {
    playInline: true
}

It does not allow adjustment.
Can you include it with the update?

**Comment by vinayakkulkarni** [comment]
Will try and check if I can do it.. Right now a bit busy.

**Comment by yunusberkayaksoy** [comment]
Dude would you check at a suitable time?

**Comment by vinayakkulkarni** [comment]
@yunusberkayaksoy Can you please test? Thanks
